# Generated by Django 2.1.3 on 2018-11-19 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='asignacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Grado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grado', models.CharField(max_length=60)),
                ('seccion', models.CharField(max_length=60)),
                ('encargado', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materia', models.CharField(max_length=60)),
                ('creditos', models.IntegerField()),
                ('profesor', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='grado',
            name='materias',
            field=models.ManyToManyField(through='examen.asignacion', to='examen.Materia'),
        ),
        migrations.AddField(
            model_name='asignacion',
            name='Grado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examen.Grado'),
        ),
        migrations.AddField(
            model_name='asignacion',
            name='Materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examen.Materia'),
        ),
    ]
